(** Spinner animations for terminal UI.

    Spinners are from cli-spinners: MIT License Copyright (c) Sindre Sorhus
    <sindresorhus@gmail.com> (sindresorhus.com) *)

type spinner_kind =
  (* Braille patterns *)
  | Braille_dots  (** Classic rotating braille dots: ⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏ *)
  | Braille_dots2  (** Alternative braille dots: ⣾⣽⣻⢿⡿⣟⣯⣷ *)
  | Braille_dots3  (** Third braille variation: ⠋⠙⠚⠞⠖⠦⠴⠲⠳⠓ *)
  | Braille_dots4  (** Bouncing braille dots *)
  | Braille_dots5  (** Complex braille cycle *)
  | Braille_dots6  (** Extended braille animation *)
  | Braille_dots7  (** Another braille pattern *)
  | Braille_dots8  (** Long braille sequence *)
  | Braille_dots9  (** Vertical braille: ⢹⢺⢼⣸⣇⡧⡗⡏ *)
  | Braille_dots10  (** Small braille set: ⢄⢂⢁⡁⡈⡐⡠ *)
  | Braille_dots11  (** Simple braille cycle *)
  | Braille_dots12  (** Two-column braille animation *)
  | Braille_dots13  (** Dense braille: ⣼⣹⢻⠿⡟⣏⣧⣶ *)
  | Braille_dots14  (** Two-character braille patterns *)
  | Braille_8bit  (** Full 8-bit braille character set *)
  | Braille_circle  (** Circular braille motion *)
  | Braille_sand  (** Sand falling effect with braille *)
  (* Line and ASCII *)
  | Line_spin  (** Simple line rotation: - \ | / *)
  | Line_pulse  (** Pulsing line: ⠂-–—–- *)
  | Pipe_spin  (** Box drawing rotation: ┤┘┴└├┌┬┐ *)
  | Ascii_dots  (** Simple ASCII dots: . .. ... *)
  | Ascii_dots_scroll  (** Scrolling ASCII dots *)
  | Ascii_star  (** ASCII star rotation: + x * *)
  | Ascii_flip  (** Flipping characters: _ - ` ' ´ *)
  | Ascii_hamburger  (** Hamburger menu: ☱☲☴ *)
  | Ascii_binary  (** Binary numbers animation *)
  | Ascii_dqpb  (** Letters d q p b rotation *)
  (* Bars and blocks *)
  | Bar_vertical_grow  (** Growing vertical bar: ▁▃▄▅▆▇ *)
  | Bar_horizontal_grow  (** Growing horizontal bar: ▏▎▍▌▋▊▉ *)
  | Bar_bounce  (** Bouncing bar: [=   ] [==  ] *)
  | Block_bounce  (** Bouncing block corners: ▖▘▝▗ *)
  | Block_wave  (** Wave with blocks: ▌▀▐▄ *)
  | Block_square  (** Square toggle: □■ *)
  | Block_squish  (** Squishing blocks: ╫╪ *)
  (* Geometric shapes *)
  | Triangle_spin  (** Rotating triangle: ◢◣◤◥ *)
  | Square_corners  (** Rotating square corners: ◰◳◲◱ *)
  | Circle_quarters  (** Circle quarters: ◴◷◶◵ *)
  | Circle_halves  (** Circle halves: ◐◓◑◒ *)
  | Circle_simple  (** Simple circle: ◡⊙◠ *)
  | Arc_spin  (** Arc rotation: ◜◠◝◞◡◟ *)
  (* Progress indicators *)
  | Progress_bar  (** Material design progress bar *)
  | Progress_balloon  (** Balloon expansion: . o O @ * *)
  | Progress_balloon2  (** Alternative balloon: . o O ° *)
  | Progress_layer  (** Layered progress: - = ≡ *)
  | Progress_point  (** Moving point: ∙∙∙ ●∙∙ ∙●∙ *)
  | Progress_beta_wave  (** Beta wave: ρββββββ *)
  (* Animations *)
  | Anim_pong  (** Pong game animation *)
  | Anim_shark  (** Swimming shark *)
  | Anim_grenade  (** Exploding grenade *)
  | Anim_ball_bounce  (** Bouncing ball in parentheses *)
  | Anim_aesthetic  (** Aesthetic wave: ▰▱▱▱▱▱▱ *)
  | Anim_dwarf_fortress  (** Dwarf Fortress style animation *)
  (* Noise and effects *)
  | Noise_fade  (** Fading noise: ▓▒░ *)
  | Effect_dots_bounce  (** Simple bouncing dots: ⠁⠂⠄⠂ *)
  (* Toggle animations *)
  | Toggle_box  (** Box toggle: ▫▪ *)
  | Toggle_box2  (** Alternative box: ⊶⊷ *)
  | Toggle_square  (** Square toggle: □■ *)
  | Toggle_square2  (** Multi-state square: ■□▪▫ *)
  | Toggle_square3  (** Bold square: ▮▯ *)
  | Toggle_circle  (** Circle toggle: ဝ၀ *)
  | Toggle_circle2  (** Filled circles: ⦾⦿ *)
  | Toggle_circle3  (** Dotted circles: ◍◌ *)
  | Toggle_circle4  (** Bold circles: ◉◎ *)
  | Toggle_circle5  (** Numbered circles: ㊂㊀㊁ *)
  | Toggle_diamond  (** Diamond toggle: ⧇⧆ *)
  | Toggle_shogi  (** Shogi pieces: ☗☖ *)
  | Toggle_equals  (** Equals toggle: = * - *)
  (* Arrows *)
  | Arrow_rotate  (** Rotating arrows: ←↖↑↗→↘↓↙ *)
  | Arrow_rotate2  (** Emoji arrows: ⬆️↗️➡️↘️⬇️↙️⬅️↖️ *)
  | Arrow_progress  (** Arrow progress: ▹▹▹▹▹ ▸▹▹▹▹ *)
  (* Unicode and emoji *)
  | Unicode_star_pulse  (** Star pulse: ✶✸✹✺✹✷ *)
  | Unicode_moon_phases  (** Moon phases: 🌑🌒🌓🌔🌕🌖🌗🌘 *)
  | Unicode_earth_rotate  (** Earth rotation: 🌍🌎🌏 *)
  | Unicode_clock  (** Clock faces: 🕛🕐🕑... *)
  | Unicode_weather  (** Weather cycle: ☀️🌤⛅️🌥☁️🌧 *)
  (* Emoji animations *)
  | Emoji_hearts  (** Colored hearts: 💛💙💜💚❤️ *)
  | Emoji_monkey  (** See/hear/speak no evil: 🙈🙉🙊 *)
  | Emoji_faces  (** Face expressions: 😄😝 *)
  | Emoji_runner  (** Running figure: 🚶🏃 *)
  | Emoji_christmas  (** Christmas trees: 🌲🎄 *)
  | Emoji_finger_dance  (** Hand gestures: 🤘🤟🖖✋🤚👆 *)
  | Emoji_fist_bump  (** Fist bump animation *)
  | Emoji_soccer  (** Soccer header animation *)
  | Emoji_mindblown  (** Mind blown sequence *)
  | Emoji_speaker  (** Speaker volume: 🔈🔉🔊 *)
  (* Pulse animations *)
  | Pulse_orange  (** Orange pulse: 🔸🔶🟠 *)
  | Pulse_blue  (** Blue pulse: 🔹🔷🔵 *)
  | Pulse_orange_blue  (** Combined orange/blue pulse *)
  (* Special *)
  | Time_travel  (** Clock time travel effect *)
  (* Custom *)
  | Custom of { frames : string list; interval : int }
      (** Custom animation frames *)

val spinner : ?speed:float -> ?time:float -> spinner_kind -> Element.t
