(** ANSI terminal escape sequences.

    Escape sequences are represented as functions ({!type-t}) that write
    directly to a {!writer} buffer. Combining sequences creates a new function,
    not a new string.

    For quick one-off output, convert to a string with {!to_string}:
    {[
    Ansi.(to_string (cursor_position ~row:10 ~col:5))
    ]}

    For render loops, use {!emit} with a pre-allocated buffer:
    {[
    let buf = Bytes.create 65536 in
    let w = Ansi.Writer.make buf in
    Ansi.emit (Ansi.cursor_position ~row:1 ~col:1) w;
    Ansi.emit (Ansi.literal "Hello") w
    ]}

    For hot loops where even closure allocation matters, use {!sgr_direct} or
    {!Sgr_state} which write directly to the buffer. *)

(** {1:types Types} *)

type writer = Writer.t
(** The type for byte buffer writers. See {!Writer}. *)

type t = writer -> unit
(** The type for escape sequences. A function that writes bytes to a {!writer}.
    Sequences compose by function application. *)

(** {1:combinators Sequence combinators} *)

val empty : t
(** [empty] emits nothing. *)

val literal : string -> t
(** [literal s] emits [s] verbatim. *)

val char : char -> t
(** [char c] emits [c]. *)

val concat : t -> t -> t
(** [concat a b] emits [a] then [b]. *)

val seq : t list -> t
(** [seq xs] emits the sequences in [xs] in order. *)

val bytes : bytes -> off:int -> len:int -> t
(** [bytes b ~off ~len] copies a byte slice to the writer.

    Raises [Invalid_argument] if the slice is out of bounds. *)

val utf8 : int -> t
(** [utf8 cp] encodes Unicode scalar value [cp] as UTF-8. Invalid codepoints
    (negative, > 0x10FFFF, or surrogates 0xD800–0xDFFF) are replaced with
    U+FFFD. *)

(** {1:output Output} *)

val emit : t -> writer -> unit
(** [emit seq w] applies [seq] to [w]. *)

val to_string : t -> string
(** [to_string seq] converts [seq] to a string. Allocates a temporary buffer. *)

val to_buffer : t -> Buffer.t -> unit
(** [to_buffer seq buf] appends [seq] to [buf]. Allocates an intermediate string
    via {!to_string}. *)

(** {1:csi CSI and SGR primitives} *)

val esc : string -> t
(** [esc body] emits [ESC \[ body]. *)

val csi : params:string -> command:char -> t
(** [csi ~params ~command] emits [ESC \[ params command]. *)

val sgr : int list -> t
(** [sgr codes] emits [ESC \[ codes m]. [sgr []] emits nothing; use {!reset} or
    [sgr [0]] to clear attributes. *)

val sgr_direct : ((int -> unit) -> unit) -> writer -> unit
(** [sgr_direct f w] emits SGR codes generated by callback [f]. The callback
    receives a [push] function; every call to [push code] appends that integer
    to the SGR parameter list. Avoids list allocation. *)

val reset : t
(** [reset] emits [ESC \[ 0 m]. *)

(** {1:cursor Cursor control} *)

(** {2:cursor_rel Relative movement} *)

val cursor_up : n:int -> t
(** [cursor_up ~n] moves the cursor up [n] lines. Negative values are clamped to
    0. *)

val cursor_down : n:int -> t
(** [cursor_down ~n] moves the cursor down [n] lines. *)

val cursor_forward : n:int -> t
(** [cursor_forward ~n] moves the cursor right [n] columns. *)

val cursor_back : n:int -> t
(** [cursor_back ~n] moves the cursor left [n] columns. *)

val cursor_next_line : n:int -> t
(** [cursor_next_line ~n] moves down [n] lines to column 1 (CNL). *)

val cursor_previous_line : n:int -> t
(** [cursor_previous_line ~n] moves up [n] lines to column 1 (CPL). *)

(** {2:cursor_abs Absolute positioning} *)

val cursor_horizontal_absolute : int -> t
(** [cursor_horizontal_absolute col] moves to 1-based column [col]. Values < 1
    are clamped to 1. *)

val cursor_vertical_absolute : int -> t
(** [cursor_vertical_absolute row] moves to 1-based row [row]. Values < 1 are
    clamped to 1. *)

val cursor_position : row:int -> col:int -> t
(** [cursor_position ~row ~col] moves to 1-based [(row, col)]. *)

(** {2:cursor_state State} *)

val cursor_save : t
(** [cursor_save] saves cursor position (CSI s). Must be paired with
    {!cursor_restore}. *)

val cursor_restore : t
(** [cursor_restore] restores cursor position (CSI u). Behaviour is undefined
    without a prior {!cursor_save}. *)

(** {2:cursor_appearance Appearance} *)

type cursor_shape =
  [ `Default
  | `Blinking_block
  | `Block
  | `Blinking_underline
  | `Underline
  | `Blinking_bar
  | `Bar ]
(** The type for cursor shapes (DECSCUSR). *)

val cursor_style : shape:cursor_shape -> t
(** [cursor_style ~shape] sets the cursor shape. *)

type cursor_style = [ `Block | `Line | `Underline ]
(** The type for cursor shapes without a blink flag. This is the vocabulary
    shared by {!Terminal} and {!Screen}; pair with a blinking flag to select a
    {!cursor_shape} via {!cursor_shape_of_style}. *)

val cursor_shape_of_style : style:cursor_style -> blinking:bool -> cursor_shape
(** [cursor_shape_of_style ~style ~blinking] is the DECSCUSR {!cursor_shape}
    selecting [style] with blink [blinking]. *)

val cursor_color : r:int -> g:int -> b:int -> t
(** [cursor_color ~r ~g ~b] sets the cursor color (OSC 12). Pair with
    {!reset_cursor_color} or {!reset_cursor_color_fallback} during teardown. *)

val reset_cursor_color : t
(** [reset_cursor_color] resets the cursor color (OSC 112). *)

val reset_cursor_color_fallback : t
(** [reset_cursor_color_fallback] resets the cursor color using
    [OSC 12 "default"]. Fallback for terminals without OSC 112. *)

(** {1:screen Screen control} *)

val clear : t
(** [clear] erases the visible screen (ED 2) without moving the cursor. *)

val home : t
(** [home] moves the cursor to (1, 1). *)

val clear_and_home : t
(** [clear_and_home] moves to home then clears the screen. *)

type erase_display_mode = [ `Below | `Above | `All | `Scrollback ]
(** The type for erase display modes. *)

val erase_display : mode:erase_display_mode -> t
(** [erase_display ~mode] erases parts of the screen (ED). *)

val erase_below_cursor : t
(** [erase_below_cursor] clears from cursor to end of screen (ED 0). *)

type erase_line_mode = [ `Right | `Left | `All ]
(** The type for erase line modes. *)

val erase_line : mode:erase_line_mode -> t
(** [erase_line ~mode] erases parts of the current line (EL). *)

val insert_lines : n:int -> t
(** [insert_lines ~n] inserts [n] blank lines at the cursor. *)

val delete_lines : n:int -> t
(** [delete_lines ~n] deletes [n] lines at the cursor. *)

val scroll_up : n:int -> t
(** [scroll_up ~n] scrolls the viewport up by [n] lines (SU). *)

val scroll_down : n:int -> t
(** [scroll_down ~n] scrolls the viewport down by [n] lines (SD). *)

val set_scrolling_region : top:int -> bottom:int -> t
(** [set_scrolling_region ~top ~bottom] restricts scrolling to rows [top]
    through [bottom]. [top] must be >= 1 and [bottom] > [top].

    Raises [Invalid_argument] if bounds are invalid. *)

val reset_scrolling_region : t
(** [reset_scrolling_region] resets the scrolling region to the full screen. *)

(** {1:colors Colors and attributes} *)

val set_foreground : r:int -> g:int -> b:int -> t
(** [set_foreground ~r ~g ~b] sets the foreground to truecolor RGB. Components
    are clamped to \[0, 255\]. *)

val set_background : r:int -> g:int -> b:int -> t
(** [set_background ~r ~g ~b] sets the background to truecolor RGB. *)

val reset_foreground : t
(** [reset_foreground] resets the foreground to terminal default (SGR 39). *)

val reset_background : t
(** [reset_background] resets the background to terminal default (SGR 49). *)

(** {1:terminal Terminal properties} *)

val set_title : title:string -> t
(** [set_title ~title] sets the window title (OSC 0). *)

val explicit_width : width:int -> text:string -> t
(** [explicit_width ~width ~text] renders [text] as [width] cells wide (OSC 66).
    The text payload is emitted verbatim; ensure [text] does not contain
    unescaped ST sequences. *)

val explicit_width_bytes : width:int -> bytes:bytes -> off:int -> len:int -> t
(** [explicit_width_bytes ~width ~bytes ~off ~len] is like {!explicit_width} but
    writes directly from a byte buffer. *)

(** {1:osc Operating System Commands (OSC)} *)

type terminator = [ `Bel | `St ]
(** The type for OSC terminators. *)

val osc : ?terminator:terminator -> payload:string -> t
(** [osc ~terminator ~payload] emits an OSC sequence. [terminator] defaults to
    [`St]. *)

(** {2:hyperlinks Hyperlinks (OSC 8)} *)

val hyperlink_start : ?params:string -> url:string -> t
(** [hyperlink_start ~params ~url] opens a hyperlink. [params] defaults to [""]
    and holds optional key=value pairs. Must be paired with {!hyperlink_end}. *)

val hyperlink_end : t
(** [hyperlink_end] closes the current hyperlink. *)

val hyperlink : ?params:string -> url:string -> text:string -> t
(** [hyperlink ~params ~url ~text] emits a complete linked text segment. *)

(** {1:modes Terminal modes} *)

(** The type for DEC private modes. *)
type mode =
  | Cursor_visible  (** DECTCEM 25. *)
  | Mouse_tracking  (** DECSET 1000 — basic click. *)
  | Mouse_button_tracking  (** DECSET 1002 — button events. *)
  | Mouse_motion  (** DECSET 1003 — all motion. *)
  | Mouse_sgr  (** DECSET 1006 — SGR extended coords. *)
  | Mouse_sgr_pixel  (** DECSET 1016 — SGR pixel coords. *)
  | Mouse_x10  (** DECSET 9 — legacy X10. *)
  | Urxvt_mouse  (** DECSET 1015. *)
  | Alternate_screen  (** DECSET 1049. *)
  | Focus_tracking  (** DECSET 1004. *)
  | Bracketed_paste  (** DECSET 2004. *)
  | Sync_output  (** DECSET 2026. *)
  | Unicode  (** DECSET 2027. *)
  | Color_scheme  (** DECSET 2031. *)

val enable : mode -> t
(** [enable m] emits the DECSET sequence for [m]. *)

val disable : mode -> t
(** [disable m] emits the DECRST sequence for [m]. *)

(** {2:keyboard Keyboard encoding} *)

val csi_u_push : flags:int -> t
(** [csi_u_push ~flags] pushes Kitty keyboard protocol flags. *)

val csi_u_pop : t
(** [csi_u_pop] pops the Kitty keyboard protocol state. *)

val modify_other_keys_on : t
(** [modify_other_keys_on] enables Xterm modifyOtherKeys (level 1). *)

val modify_other_keys_off : t
(** [modify_other_keys_off] disables modifyOtherKeys. *)

(** {1:queries Device and capability queries} *)

(** The type for terminal queries. The terminal responds asynchronously; parse
    responses via {!Parser}. *)
type query =
  | Cursor_position  (** DSR 6. *)
  | Pixel_size  (** CSI 14 t. *)
  | Device_attributes  (** DA1. *)
  | Tertiary_attributes  (** DA3. *)
  | Terminal_identity  (** XTVERSION. *)
  | Device_status  (** DSR 5. *)
  | Csi_u_support  (** CSI ? u. *)
  | Kitty_graphics  (** Kitty graphics probe. *)
  | Sixel_geometry  (** Sixel geometry limits. *)
  | Explicit_width_support  (** OSC 66 width probe. *)
  | Scaled_text_support  (** OSC 66 scaled text probe. *)
  | Focus_mode  (** DECRQM 1004. *)
  | Sgr_pixels_mode  (** DECRQM 1016. *)
  | Bracketed_paste_mode  (** DECRQM 2004. *)
  | Sync_mode  (** DECRQM 2026. *)
  | Unicode_mode  (** DECRQM 2027. *)
  | Color_scheme_mode  (** DECRQM 2031. *)

val query : query -> t
(** [query q] emits the query sequence for [q]. *)

(** {1:convenience High-level convenience} *)

val render : ?hyperlinks_enabled:bool -> (Style.t * string) list -> string
(** [render ~hyperlinks_enabled segs] renders styled segments to a string. Emits
    minimal SGR transitions by tracking terminal state. Closes open hyperlinks
    and appends a final reset.

    [hyperlinks_enabled] defaults to [true]; when [false], suppresses OSC 8
    sequences. *)

val parse : string -> Parser.token list
(** [parse s] tokenizes [s] into ANSI tokens. Never raises; malformed sequences
    become {!Parser.Unknown} controls. *)

val strip : string -> string
(** [strip s] removes all ANSI escape sequences from [s], returning plain text
    only. *)

(** {1:submodules Sub-modules} *)

module Writer = Writer
(** Byte buffer writers. *)

module Color = Color
(** Terminal colors. *)

module Attr = Attr
(** Text attribute flags. *)

module Style = Style
(** Terminal text styles. *)

module Parser = Parser
(** Streaming escape sequence parser. *)

module Sgr_state = Sgr_state
(** SGR state tracker for render loops. *)
