(executable
 (name bench_ansi)
 (modules bench_ansi)
 (libraries thumper matrix.ansi))

(executable
 (name bench_text)
 (modules bench_text)
 (libraries thumper matrix.text))

(executable
 (name bench_input)
 (modules bench_input)
 (libraries thumper matrix.input))

(executable
 (name bench_grid)
 (modules bench_grid)
 (libraries thumper matrix.grid matrix.ansi))

(executable
 (name bench_screen)
 (modules bench_screen)
 (libraries thumper matrix.screen matrix.grid matrix.ansi))

(executable
 (name bench_runtime)
 (modules bench_runtime)
 (libraries thumper matrix))

(rule
 (alias bench)
 (locks /bench)
 (action
  (progn
   (run %{exe:bench_ansi.exe})
   (diff? ansi.thumper ansi.thumper.corrected))))

(rule
 (alias bench)
 (locks /bench)
 (action
  (progn
   (run %{exe:bench_text.exe})
   (diff? text.thumper text.thumper.corrected))))

(rule
 (alias bench)
 (locks /bench)
 (action
  (progn
   (run %{exe:bench_input.exe})
   (diff? input.thumper input.thumper.corrected))))

(rule
 (alias bench)
 (locks /bench)
 (action
  (progn
   (run %{exe:bench_grid.exe})
   (diff? grid.thumper grid.thumper.corrected))))

(rule
 (alias bench)
 (locks /bench)
 (action
  (progn
   (run %{exe:bench_screen.exe})
   (diff? screen.thumper screen.thumper.corrected))))

(rule
 (alias bench)
 (locks /bench)
 (action
  (progn
   (run %{exe:bench_runtime.exe})
   (diff? runtime.thumper runtime.thumper.corrected))))
