(library
 (instrumentation
  (backend ppx_windtrap.coverage))
 (instrumentation
  (backend ppx_windtrap.mutate))
 (name matrix_terminal)
 (public_name matrix.terminal)
 (libraries unix matrix.ansi matrix.input matrix.text)
 (private_modules caps)
 (foreign_stubs
  (language c)
  (names terminal_stubs)))
